{% set version = "0.4.8" %}

package:
  name: osc
  version: {{ version }}

source:
  url: https://github.com/theimpostor/osc/archive/v{{ version }}.tar.gz
  sha256: cfe4e92c7190e3a0db8131a01ec8f9215334ea78ce9a99d8a2db29217acf094d

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - osc --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Access the system clipboard from anywhere using the ANSI OSC52 sequence
  home: https://github.com/theimpostor/osc
  dev_url: https://github.com/theimpostor/osc

extra:
  recipe-maintainers:
    - danielnachun
